version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.22
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set npm credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Yarn build and publish package
          command: |
            yarn build
            VERSIONS=$(npm view vue-news versions)
            CURRENT_VERSION=$(npm view vue-news version)
            if [[ ! " ${VERSIONS[@]} " =~ $CURRENT_VERSION ]]; then
              npm publish
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master